---
title: dplyr tutorial
format: html
---

```{r Setup}
library(tidyverse)
```

```{r across()}
# across()
starwars %>% 
  summarise(across(height:mass, mean, na.rm = TRUE))

starwars %>% 
  summarise(across(where(is.numeric), median, na.rm = TRUE))

# More than one function
starwars %>% 
  summarise(across(where(is.numeric),
                   list(min = min, max = max, mean = mean),
                   na.rm = TRUE))

# Function syntax
starwars %>% 
  summarise(across(where(is.numeric),
                   list( ~ min(.x, na.rm = TRUE),
                         ~ max(.x, na.rm = TRUE),
                         ~ mean(.x, na.rm = TRUE))))

# Find # of unique values in character variables
summary(starwars)

starwars %>% 
  summarise(length(unique(hair_color)))

starwars %>% distinct(hair_color) %>% count() #nrow()

starwars %>% 
  summarise(across(where(is.character), ~ length(unique(.x))))

starwars %>% 
  group_by(species) %>% 
  filter(n() > 1) %>% 
  summarise(across(c(sex, gender, homeworld),
                   ~ length(unique(.x))),
            n = n())

# Controlling names
starwars %>%
  summarise(across(where(is.numeric),
                   list(min = min, max = max, mean = mean), na.rm = TRUE,
                   .names = '{.fn} of {.col}'))

# Show rows with no missing values
starwars %>%
  filter(across(everything(), ~ !is.na(.x)))

starwars %>%
  count(across(contains('color')), sort = TRUE)

# Exercise - calculate median for numeric variables for each species and gender
starwars %>%
  group_by(species, gender) %>%
  summarise(across(where(is.numeric), ~ median(.x, na.rm = TRUE)))
```

```{r case_when()}
# fizz = 3, buzz = 5, fizzbuzz = 3 & 5
x <- 1:100
case_when(
  x %% 15 == 0 ~ 'fizzbuzz',
  x %% 5 == 0 ~ 'buzz',
  x %% 3 == 0 ~ 'fizz',
  TRUE ~ as.character(x)
)

# practical example using Starwars
starwars %>% 
  select(species, gender, height) %>% 
  mutate(height_cat = case_when(height > quantile(height, 3/4, na.rm = TRUE) ~ 'tall',
                                height < quantile(height, 1/4, na.rm = TRUE) ~ 'short',
                                TRUE ~ 'average'))

starwars %>%
  select(name:mass, gender, species) %>% 
  mutate(type = case_when(
    height >= 200 | mass >= 200 ~ 'large',
    species == 'Droid' ~ 'robot',
    TRUE ~ 'other'
  ))
```

```{r rownames_to_column()}
state.x77 %>% 
  as.data.frame() %>% 
  rownames_to_column('State') %>% 
  as_tibble()
```

```{r distinct()}
starwars %>%
  distinct(homeworld, species)
```

```{r rowwise()}

```

